export const GET_TICKER_POKEMON_API = 'GET_TICKER_POKEMON_API';
export const GET_TICKER_POKEMON_API_SUCCESS = 'GET_TICKER_POKEMON_API_SUCCESS';
export const GET_TICKER_POKEMON_API_ERROR = 'GET_TICKER_POKEMON_API_ERROR';